const ALLOT_WATER = "ALLOT_WATER";
const ADD_GUESTS = "ADD_GUESTS";
const BILL = "BILL";
const TWO_BEDROOM_APARTMENT = 2;
const THREE_BEDROOM_APARTMENT = 3;
const ZERO=0;
const TWO_BEDROOM_NUMBER_OF_PEOPLE=3;
const THREE_BEDROOM_NUMBER_OF_PEOPLE=5;
const FIVE_HUNDRED_LITRES=500;
const THOUSAND_LITRES=1000;
const THOUSAND_FIVE_HUNDRED_LITRES=1500;
const THREE_THOUSAND_LITRES=3000;
const DAYS_IN_A_MONTH=30;
const STANDARD_NUMBER_OF_LITRES=10;
const RATE_OF_BASIC_SLAB=2;
const RATE_OF_MEDIUM_SLAB=3;
const RATE_OF_MAJOR_SLAB=5;
const RATE_OF_ADVANCED_SLAB=8;
const RATE_OF_BOREWELL_WATER=1.5;

module.exports={
    ALLOT_WATER, 
    ADD_GUESTS,
    BILL,
    TWO_BEDROOM_APARTMENT,
    THREE_BEDROOM_APARTMENT,
    ZERO,
    TWO_BEDROOM_NUMBER_OF_PEOPLE,
    THREE_BEDROOM_NUMBER_OF_PEOPLE,
    FIVE_HUNDRED_LITRES,
    THOUSAND_LITRES,
    THOUSAND_FIVE_HUNDRED_LITRES,
    THREE_THOUSAND_LITRES,
    DAYS_IN_A_MONTH,
    STANDARD_NUMBER_OF_LITRES,
    RATE_OF_BASIC_SLAB,
    RATE_OF_MEDIUM_SLAB,
    RATE_OF_MAJOR_SLAB,
    RATE_OF_ADVANCED_SLAB,
    RATE_OF_BOREWELL_WATER
};